[options]
addons_path = /mnt/oca/donation,/mnt/oca/partner-contact,/mnt/oca/field-service,/mnt/oca/project,/mnt/oca/hr,/mnt/oca/mis-builder,/mnt/oca/reporting-engine,/mnt/oca/stock-logistics-workflow,/mnt/oca/helpdesk,/mnt/oca/knowledge,/mnt/oca/l10n-colombia,/mnt/oca/account-financial-reporting,/mnt/oca/account-invoicing,/mnt/oca/account-payment,/mnt/oca/account-financial-tools,/mnt/oca/contract,/mnt/oca/product-attribute,/mnt/oca/e-commerce,/mnt/oca/web,/mnt/oca/server-tools,/mnt/oca/server-ux,/mnt/oca/queue,/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = fundacion_kasa

; Parámetros de seguridad y proxy
proxy_mode = True
list_db = True
admin_passwd = $2b$12$K89s3LkWG1N/4YfBwH2Bse6yYw2y7vH0E0B1A1zY2z3x4v5w6

; Límites de tiempo para importaciones pesadas y reportes
limit_time_cpu = 600
limit_time_real = 1200
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648

; Hilos de trabajadores (ajustar según CPU de VPS)
workers = 2
max_cron_threads = 1